[workspace]
resolver = "2"
members = [
    "anker",
    "cli",
    "multisig/programs/multisig",
    "program",
    "testlib",
]

# Ensure that we don't leave half a program running if something in a thread panics.
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
