name: maintainer

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:

  build_maintainer_image:
     runs-on: ubuntu-latest
     continue-on-error: true

     steps:
       - name: Build maintainer image
         uses: actions/checkout@v2
         with:
           submodules: true

       - name: Build Docker image
         run: |
           export SOLIDO_VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///g')
           docker-compose -f docker/docker-compose.yml build

       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.TECHOPSDOCKERHUB_USERNAME }}
           password: ${{ secrets.TECHOPSDOCKERHUB_TOKEN }}

       - name: Push Docker image
         run: |
           export SOLIDO_VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///g')
           docker-compose -f docker/docker-compose.yml push
