name: maintainer

on:
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      version:
        description: 'Tag override for image version, i.e. v0.1.0 '
        required: true
        default: 'v0.1.0'
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:

  build_maintainer_image:
     runs-on: ubuntu-latest
     continue-on-error: true

     steps:
       - name: Build maintainer image
         uses: actions/checkout@v2
         with:
           submodules: true

       - name: Set Version
         run: |
           export SOLIDO_VERSION=${{ github.event.inputs.version || (GITHUB_REF | sed 's/refs\/tags\///g')  }}
           echo "Set image version as $SOLIDO_VERSION"

       - name: Build Docker image
         run: |
           docker-compose -f docker/docker-compose.yml build

       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.TECHOPSDOCKERHUB_USERNAME }}
           password: ${{ secrets.TECHOPSDOCKERHUB_TOKEN }}

       - name: Push Docker image
         run: |
           docker-compose -f docker/docker-compose.yml push
