name: maintainer

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Build and publish maintainer image'

env:
  CARGO_TERM_COLOR: always
  SOLIDO_VERSION: v1

jobs:

  build_maintainer_image:
     runs-on: ubuntu-latest
     continue-on-error: true

     steps:
       - name: Build maintainer image
         uses: actions/checkout@v2
         with:
           submodules: true

       - name: Build Docker image
         run: docker-compose -f docker/docker-compose.yml build

       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.TECHOPSDOCKERHUB_USERNAME }}
           password: ${{ secrets.TECHOPSDOCKERHUB_TOKEN }}

       - name: Push Docker image
         run: docker-compose -f docker/docker-compose.yml push
