name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Solana contract test
      run: |
        cd program
        sh -c "$(curl -sSfL https://release.solana.com/v1.6.7/install)"
        export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
        cargo test-bpf

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-clippy
      run: rustup component add clippy
    - name: run-clippy
      run: cargo clippy -- -W clippy::pedantic