name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: cache-build-artifacts
      uses: actions/cache@v2
      with:
        path: |
          target
          multisig/target
        key: cargo-bpf-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          cargo-bpf-${{ hashFiles('Cargo.lock') }}
          cargo-bpf

    - name: Solana contract test
      run: |
        cd program
        sudo apt-get install -y libudev-dev
        sh -c "$(curl -sSfL https://release.solana.com/v1.6.7/install)"
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        cargo test-bpf

    - name: Build and test Multisig
      run: |
        export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
        solana-test-validator > /dev/null &
        validator="$!"

        # Build the CLI while the validator is starting.
        cargo build --package multisig

        # Build the on-chain multisig program.
        cd multisig
        cargo install --git https://github.com/project-serum/anchor --tag v0.4.5 anchor-cli --locked
        export PATH="$HOME/.cargo/bin:$PATH"
        anchor build
        cd ..

        # Perform initial Solana setup.
        solana-keygen new --no-bip39-passphrase --silent
        solana config set --url http://127.0.0.1:8899
        solana airdrop 500.0

        multisig-cli/tests/test_cli.py
        kill $validator

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: cache-build-artifacts
      uses: actions/cache@v2
      with:
        path: target
        key: cargo-clippy-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          cargo-clippy-${{ hashFiles('Cargo.lock') }}
          cargo-clippy

    - name: install-clippy
      run: rustup component add clippy

    - name: run-clippy
      run: |
        sudo apt-get install -y libudev-dev
        cargo clippy -- -W clippy::pedantic

  coverage:
    runs-on:  ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: cache-build-artifacts
        uses: actions/cache@v2
        with:
          path: target
          key: cargo-tarpaulin-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-tarpaulin-${{ hashFiles('Cargo.lock') }}
            cargo-tarpaulin

      - name: Generate code coverage
        run: |
          sudo apt update
          sudo apt install libudev-dev
          cargo install --version 0.16.0 cargo-tarpaulin 
          cargo tarpaulin --verbose --workspace --out Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}} 
          fail_ci_if_error:     true
